chat_homepage:
    path:     /
    defaults: { _controller: ChatBundle:Chat:index }
    
ajax:
    pattern:  /ajax/sendmsg
    defaults: { _controller: ChatBundle:Messages:sendmsg }

load_msgs:
    pattern: /ajax/loadmsgs/{id}/{action}
    defaults: {_controller: ChatBundle:Messages:loadMsgs, id: '', action: '' }
    
edit_msg:
    pattern: /ajax/edit-msg
    defaults: {_controller: ChatBundle:Messages:editMsg}

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile